-- Actualizar video_ref con URLs de Google Drive
-- Ejecutar en Supabase → SQL Editor

UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1UAVrLOoU3sr50M2aoui99cpp20Olih5U/view?usp=drive_link' WHERE LOWER(name) = LOWER('Gemelo sentado');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1NET3J694FvDlb4Vcy2wih9RJo_rjLeUD/view?usp=drive_link' WHERE LOWER(name) = LOWER('Gemelo de pie en multipower sobre step');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1rXM97vg5coD83yChf5dOLFyBuh8q-PCj/view?usp=drive_link' WHERE LOWER(name) = LOWER('Gemelo prensa 45°');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/13_AhmQ2LJQwvpVohdk3sWU_l41KcudKY/view?usp=drive_link' WHERE LOWER(name) = LOWER('Gemelo de pie en máquina (peso hombros)');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1yb5gFiojg9PSBQyA0T1wxtXj2FkrEMr0/view?usp=drive_link' WHERE LOWER(name) = LOWER('Gemelo de pie en máquina (peso cadera)');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1_45wc1HUeeuJTApJpT-0F1mta68yWf4q/view?usp=drive_link' WHERE LOWER(name) = LOWER('Gemelo hack en máquina de palanca');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1-7Cy8SEI_rJpQPDFfva0nET4z7TqfLKo/view?usp=drive_link' WHERE LOWER(name) = LOWER('Extensión de cuádriceps');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1e_eXnWrF2PPzUuWQiE66caIxIk1UG5cp/view?usp=drive_link' WHERE LOWER(name) = LOWER('Extensión de cuádriceps unilateral');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1bpI5QxKzXEDkqpwgf1xNqpr4Y91ai4pQ/view?usp=drive_link' WHERE LOWER(name) = LOWER('Prensa 45° ');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1aHe8B5TQ_gi6poKijrFTq4_oyJflIQBD/view?usp=drive_link' WHERE LOWER(name) = LOWER('Prensa 45° unilateral ');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1OQMDwb4xNKtyYVNgK76LMuQL0jV6mtkH/view?usp=drive_link' WHERE LOWER(name) = LOWER('Prensa horizontal en máquina de placas ');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1QgH7W-nlJwJHAHW_prGjs-n7_1z_mUZG/view?usp=drive_link' WHERE LOWER(name) = LOWER('Prensa horizontal unilateral en máquina de placas');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1GkMpwkdoPg_K2UOZ55NiiFqdfbMf4RzR/view?usp=drive_link' WHERE LOWER(name) = LOWER('Prensa horizontal en máquina de palanca');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/185DytpoiLCGCzjvW4XbuxU7jZfxyP2MK/view?usp=drive_link' WHERE LOWER(name) = LOWER('Prensa horizontal unilateral en máquina de palanca');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1MV9XmKzw6cd9yRnGhcnDkBy77twFHLb8/view?usp=drive_link' WHERE LOWER(name) = LOWER('Sentadilla pendular en máquina de palanca');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1PtrycTFVVspXaRf1YrR8PMuWdTaukCkg/view?usp=drive_link' WHERE LOWER(name) = LOWER('Sentadilla libre');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1b0H5hIB2CVrkkNhoRbIM5JA_n7q2vM7R/view?usp=drive_link' WHERE LOWER(name) = LOWER('Sentadilla barra safety');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1SAIi9Bzw7fp-36eI4LZLFKf7wt6TM5At/view?usp=drive_link' WHERE LOWER(name) = LOWER('Sentadilla hack 60° inclinada');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1IgScMSfNuO5zmoOFTpj1ZOSy4fyUMBs0/view?usp=drive_link' WHERE LOWER(name) = LOWER('Sentadilla hack palanca');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1H-SP2X3F-I7oyiDPnpzy6q-P6lm14zyK/view?usp=drive_link' WHERE LOWER(name) = LOWER('Sentadilla multipower');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1jpnnl-oyn6tE79xcj2C_WTivShZjJlPA/view?usp=drive_link' WHERE LOWER(name) = LOWER('Sentadilla box');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1X0D6tZ7V8dD_ZaNRZyf6R7ih9R6-5Jrv/view?usp=drive_link' WHERE LOWER(name) = LOWER('Sentadilla sissy');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1zVJ7WXlDxjeAiweX55atreqbDHryk25n/view?usp=drive_link' WHERE LOWER(name) = LOWER('Zancada libre estática');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/16vEk49gYPaFO2AkTUHakug2MgnrtaRxD/view?usp=drive_link' WHERE LOWER(name) = LOWER('Zancada en multipower');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1cqNm_dEnnKWDtb6awlgb2BDNk40yOuQE/view?usp=drive_link' WHERE LOWER(name) = LOWER('Femoral sentado');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1b3CPRt-KVwF2Gd_AezR5xhYjJExldyL9/view?usp=drive_link' WHERE LOWER(name) = LOWER('Femoral sentado unilateral');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1T4OHLu2cqPkeiTZ8KF_8vuC6gYVemVHG/view?usp=drive_link' WHERE LOWER(name) = LOWER('Femoral tumbado ');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/17hDHImNzUi6QoxPrF7s5F7dg00WYCe1O/view?usp=drive_link' WHERE LOWER(name) = LOWER('Femoral tumbado unilateral');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1brGcjpC9HeDbNyDc5hYMln4ekb9JHg0W/view?usp=drive_link' WHERE LOWER(name) = LOWER('Femoral de pie en máquina unilateral');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/10C9onLJKCFWX0MQ7JUF3clDgwuTbrG0S/view?usp=drive_link' WHERE LOWER(name) = LOWER('Prensa 45° pies parte alta ');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1kKggw8i3jzkzQxbdoass_W1FHKHPNWfP/view?usp=drive_link' WHERE LOWER(name) = LOWER('Prensa horizontal unilateral pies parte alta máquina de placas');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1aY8DtvsJvb-qAgCJE8BQYBv4GzRfAKnr/view?usp=drive_link' WHERE LOWER(name) = LOWER('Peso muerto rumano con barra libre');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1d7YNZ9yQM9fn773UxZ0KM6brxDvWOTBZ/view?usp=drive_link' WHERE LOWER(name) = LOWER('Peso muerto rumano con barra libre piernas rígidas');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1KJUjQTmuh05KTcCcsXo84dZnlMDY4Nxy/view?usp=drive_link' WHERE LOWER(name) = LOWER('Peso muerto rumano con mancuernas');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1DbIEcXHAN3VazaDLqsTKGF546KHXOFkv/view?usp=drive_link' WHERE LOWER(name) = LOWER('Peso muerto rumano con mancuernas unilateral');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1JKPfM2baEes8yihY41b8MqSfR9qC4PG0/view?usp=drive_link' WHERE LOWER(name) = LOWER('Peso muerto rumano en multipower');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1UKqtcRTaiV3ZIL0rXoBAwMYVFLTvP7bW/view?usp=drive_link' WHERE LOWER(name) = LOWER('Peso muerto rumano en punta');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1fPHvbuCzlfP9eEP-bJYhNWpzhX3NbCfG/view?usp=drive_link' WHERE LOWER(name) = LOWER('Peso muerto rumano en hack de palanca (peso hombros, buenos días)');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1J2s1l_wl9CTk8EkfxwOeFrq-F7k5uxgP/view?usp=drive_link' WHERE LOWER(name) = LOWER('Prensa horizontal placas pies parte alta');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1doyBN_wlwishzp6cf_WNsAAnRJbTiiyG/view?usp=drive_link' WHERE LOWER(name) = LOWER('Hip trust en máquina de palanca');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1TluOEs98L_4MeQxzg7y51zSyfbsYJye1/view?usp=drive_link' WHERE LOWER(name) = LOWER('Hip trust libre (espalda apoyada en banco)');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1j4ssKyrco9tnxy9v17j8UUM6S5s_Xh71/view?usp=drive_link' WHERE LOWER(name) = LOWER('Hip trust en el suelo con discos Bumper');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1fBMhYODH9Vq_bkOIeTN5nsMfGtGyfkE_/view?usp=drive_link' WHERE LOWER(name) = LOWER('Hip trust unilateral en el suelo');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1sNjSSPgEaH35RRVLd5NQy5JDn_8oQf8H/view?usp=drive_link' WHERE LOWER(name) = LOWER('Patada de glúteo desde polea baja');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1re7GQmcUeR-0Csd-k5ZKL3fMPNhLUNax/view?usp=drive_link' WHERE LOWER(name) = LOWER('Patada de glúteo en cuadrupedia sobre banco desde polea baja');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1E1i1NNEOWeC3TTSlVBohlPkCQQWTVvoF/view?usp=drive_link' WHERE LOWER(name) = LOWER('Patada de glúteo acostada desde polea baja');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1DI6_hJ7QQ0CiwGyUHg_ydY0hxuDvFPh1/view?usp=drive_link' WHERE LOWER(name) = LOWER('Patada de rana en multipower');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/13q5RHA9QG-gN9d2GvIOrgQEZMDW_HizA/view?usp=drive_link' WHERE LOWER(name) = LOWER('Patada de glúteo en máquina de palanca');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1uz6RVhd67UlUSl23_XRX6fciV3tqEWOc/view?usp=drive_link' WHERE LOWER(name) = LOWER('Patada de glúteo en máquina de placas');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1sE6WkFzwA3zEHhywPmkvciU_JY_AGeaX/view?usp=drive_link' WHERE LOWER(name) = LOWER('Patada de glúteo en banco inclinado a 75° desde polea baja');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1L0kycYnXUmt5wIKtnd_SbrkhGC66vg5T/view?usp=drive_link' WHERE LOWER(name) = LOWER('Pull through desde polea baja con cuerda');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1had_jmjTgU4f_AMsqk6OncGdZrCc_amz/view?usp=drive_link' WHERE LOWER(name) = LOWER('Pull through arrodillada desde polea baja');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1plEASXVOEi3dLh816mRIHBRFIJUDMqZx/view?usp=drive_link' WHERE LOWER(name) = LOWER('Zancada al cajón ');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1u8gVUSDU1WhTxdrnnjaGFMX_Vd9u0GQy/view?usp=drive_link' WHERE LOWER(name) = LOWER('Zancada en multipower');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1Iy5duJKnjKRjw_g2uf38m_eVdlkjLDfR/view?usp=drive_link' WHERE LOWER(name) = LOWER('Zancada libre con mancuerna o kettlebell');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1kNOCWQhVAb7ybmEVyynoVcSWttqnbZx4/view?usp=drive_link' WHERE LOWER(name) = LOWER('Zancada en máquina de ayuda de dominadas');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/11srbBOtmmKiDVBEVPeCcROVz2Ssi2e8c/view?usp=drive_link' WHERE LOWER(name) = LOWER('Sentadilla de rodillas en multipower');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/10v_OaakewvdOpq0SFSkx3z8WHit5E44m/view?usp=drive_link' WHERE LOWER(name) = LOWER('Sentadilla búlgara en multipower');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1EP3khYiNlwd-bByxSI8BtrXhdlQPl7Ef/view?usp=drive_link' WHERE LOWER(name) = LOWER('Sentadilla búlgara con mancuerna');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1NZXHomMQYf08ZpUJ6Kn8IFjsDjQKFXwf/view?usp=drive_link' WHERE LOWER(name) = LOWER('Sentadilla globet');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1bffRgQWahK0WqRgtYMJeCsPXNZusBs4w/view?usp=drive_link' WHERE LOWER(name) = LOWER('Sentadilla sumo libre');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1Ghvb9CEDnnA3TMmyym49nWRnqunGsR00/view?usp=drive_link' WHERE LOWER(name) = LOWER('Sentadilla sumo con mancuernas pies elevados sobre step');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1cWWf9i55APwDiMOrtNc2yHRakyQ-7ToF/view?usp=drive_link' WHERE LOWER(name) = LOWER('Sentadilla sumo landmine');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/14QKvF_gXwD6ldhv0VK5GxzbAYl_WtDFI/view?usp=drive_link' WHERE LOWER(name) = LOWER('Hiperextensiones');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1wqFeLpHgmDg-xebBB67BKEZy-kwEGev1/view?usp=drive_link' WHERE LOWER(name) = LOWER('Presa vertical en máquina de palanca');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1_ol9e1uNxCZdIpHISCZ7aa2NiDC4AkRK/view?usp=drive_link' WHERE LOWER(name) = LOWER('Belt squat');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1QBbMym6V_TJSXpUZxyxWpo9ySbsp-Tdq/view?usp=drive_link' WHERE LOWER(name) = LOWER('Aductor sentado en máquina');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1gf8zH0RBeTwOQioWIRnTx1SGcV_FSwiz/view?usp=drive_link' WHERE LOWER(name) = LOWER('Aductor de pie desde polea baja');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1A-qVS3F8yqW9OjnbAC8-Unxls9y0smPA/view?usp=drive_link' WHERE LOWER(name) = LOWER('Abductor sentado en máquina');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1cX2uBR2NydWcFXP3SnzBRAulhXjx7gpf/view?usp=drive_link' WHERE LOWER(name) = LOWER('Abductor de pie desde polea baja');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1uJW7R9D4g9yxCO6r7JXUMb1gJt0PqQzD/view?usp=drive_link' WHERE LOWER(name) = LOWER('Aductor cophenague');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1JUGuuQVTsbXpNMYMFOMXFDP_g3ZS8t8f/view?usp=drive_link' WHERE LOWER(name) = LOWER('Abductor en cuadrupedia con banda elástica');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1tFWUTNOyHcPu83DIe3GAhX6Wh4i8im4R/view?usp=drive_link' WHERE LOWER(name) = LOWER('Abductor acostado de lado con banda elástica');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/13At9rv-qm-_5QU4InAqQkNdnTJ1hnJ7V/view?usp=drive_link' WHERE LOWER(name) = LOWER('Monster walk in squat position (flexión de rodilla 90°)');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/181SxZPt1hMHYEpkq5OR0IUYU5DrU-Jkn/view?usp=drive_link' WHERE LOWER(name) = LOWER('Encogimientos invertido desde polea alta en banco inclinado a 60°');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1oqnZZUI-OVBJQwvh7EhNQgYjPIrG9a0x/view?usp=drive_link' WHERE LOWER(name) = LOWER('Encogimientos desde polea alta sentado');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1O0ct6Dm0n7qDr35SN7kgjhsO2jwdxcxf/view?usp=drive_link' WHERE LOWER(name) = LOWER('Encogimientos en máquina ');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/14a_-kDdCaBmrIPqC74rDPbvLWykfYWRE/view?usp=drive_link' WHERE LOWER(name) = LOWER('Elevaciones de rodilla en suspensión');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1R2SRARkweyXndbSMU_NIcdYhwiF8Scsd/view?usp=drive_link' WHERE LOWER(name) = LOWER('Elevaciones de rodilla en máquina');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/149Es-qBuuy0CoxBONRu3mV8vKMDOxPwY/view?usp=drive_link' WHERE LOWER(name) = LOWER('Elevaciones de rodilla en el suelo');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1JTM-Bg_fOXL2-DaZF9Qzxa61pI2kYlh5/view?usp=drive_link' WHERE LOWER(name) = LOWER('Plancha abdominal');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1a-Aujx_vpfxrP0E4C9ROqArzBSW-VYfr/view?usp=drive_link' WHERE LOWER(name) = LOWER('Rueda abdominal');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/149Es-qBuuy0CoxBONRu3mV8vKMDOxPwY/view?usp=drive_link' WHERE LOWER(name) = LOWER('Encogimiento abdominal en el suelo');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1Is9_qzScfMVeKqWZ_FtGwzq2zNEkGkuy/view?usp=drive_link' WHERE LOWER(name) = LOWER('Remo agarre neutro anchura hombros en multiestación');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1uqQB7ShPgPHt9_CZCSyTJaJoLIlUXnLn/view?usp=drive_link' WHERE LOWER(name) = LOWER('Remo prono en multipower');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1sOEXQutWhIz-Z9-mgH4yEzBU5DtG1Bm2/view?usp=drive_link' WHERE LOWER(name) = LOWER('Remo pendlay prono');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1ExQVXar3dB0bTC6bz73hMk2guYkXh5Rl/view?usp=drive_link' WHERE LOWER(name) = LOWER('Remo con mancuerna ');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1yT-akprhPzRAcRLsQGPVDX-0zMVsIyas/view?usp=drive_link' WHERE LOWER(name) = LOWER('Remo gironda');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1aQrB4wTMuupJ93udJyIXqWTPPhy5RtZx/view?usp=drive_link' WHERE LOWER(name) = LOWER('Remo unilateral máquina de palanca neutro');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1w0o2cYanpe4H6YID0-ne4Qi9UgD8jVGv/view?usp=drive_link' WHERE LOWER(name) = LOWER('Remo unilateral neutro desde polea media banco inclinado a 60° ');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/188xdQ5tSNvH1DlhjqJiHXjlCP2-EDFnJ/view?usp=drive_link' WHERE LOWER(name) = LOWER('Remo neutro en punta unilateral ');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1ha_yfxHFImPPZ6po4mzzIIBKnWsr25mO/view?usp=drive_link' WHERE LOWER(name) = LOWER('Remo meadows unilateral');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1Qs1k-gH_nb80p3rBvFBpBBWKlrv_79-X/view?usp=drive_link' WHERE LOWER(name) = LOWER('Remo de pie en máquina de palanca unilateral');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1r3jhMFekQAvf8aK91Q1ejEvJIgsLrU6Y/view?usp=drive_link' WHERE LOWER(name) = LOWER('Remo en T agarre prono ');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/17Y11QQccdstz7WIiSTI9m9l050hzYQj0/view?usp=drive_link' WHERE LOWER(name) = LOWER('Remo en T agarre neutro');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/19fp7Cbk2uRvR5n0KRteFHG3JOjg9fb_x/view?usp=drive_link' WHERE LOWER(name) = LOWER('Seal row con mancuernas banco a 45° agarre neutro');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1w4tAVUAxeO5tcWiBTS7v65qxLK331Ait/view?usp=drive_link' WHERE LOWER(name) = LOWER('Seal row con mancuernas banco a 45° agarre prono');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1Oiw2z6UeBH3b2n3IpmHoC5eyD4DTjko4/view?usp=drive_link' WHERE LOWER(name) = LOWER('Jalón al pecho agarre neutro en multiestación (manos anchura hombros)');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1DZx8t6hAIvYuUMKBT4I1SV6KWmPAeXEE/view?usp=drive_link' WHERE LOWER(name) = LOWER('Jalón al pecho agarre prono en multiestación (manos anchura hombros)');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1-ko4tXnOqYUpffyv8FSMHcM_WePJHYTb/view?usp=drive_link' WHERE LOWER(name) = LOWER('Jalón al pecho unilateral banco inclinado a 60° desde polea alta');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/10maRmcD-p__zKLRL-XLouWYa5CCmBGdi/view?usp=drive_link' WHERE LOWER(name) = LOWER('Jalón al pecho unilateral en la multiestación arrodillado');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1r882pALMCUjBr4a4u5-0NUifWtRV7FtY/view?usp=drive_link' WHERE LOWER(name) = LOWER('Jalón al pecho agarre prono en máquina de palanca');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1kVE2HMbWG_uLZQ6yTWtu_dSrfB5_AP_s/view?usp=drive_link' WHERE LOWER(name) = LOWER('Dominadas agarre neutro');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1aK3LTtOLc3ZHLbykHLGUPicZVp6GO6xl/view?usp=drive_link' WHERE LOWER(name) = LOWER('Pullover con barra desde polea alta');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1mV_cdyNQGEQEQNFVxNfgEF7b46BvXrKA/view?usp=drive_link' WHERE LOWER(name) = LOWER('Pullover con cuerda desde polea alta');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1VdcSkL8dLQqpmFdyK1ijXEfqmWFcPBJx/view?usp=drive_link' WHERE LOWER(name) = LOWER('Pullover unilateral con muñequera desde polea alta');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1SAqRnEMecbaXqR8awS0GJqIJE6iynqfZ/view?usp=drive_link' WHERE LOWER(name) = LOWER('Pullover unilateral con cuerda desde polea alta');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1hwWR3MGdubUU617u_MKov1Em-lmVRPx3/view?usp=drive_link' WHERE LOWER(name) = LOWER('Pullover arrodillado en banco a 60° desde polea alta con barra');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1n0gGfGceEg291p4LH88eFXnrzBlWKvKx/view?usp=drive_link' WHERE LOWER(name) = LOWER('Pullover arrodillado en banco a 60° desde polea alta con cuerda');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1zcyrjHlGehX1keE3vrljqQaEBvt0U26F/view?usp=drive_link' WHERE LOWER(name) = LOWER('Jalón unilateral en máquina de palanca agarre supino');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1zcyrjHlGehX1keE3vrljqQaEBvt0U26F/view?usp=drive_link' WHERE LOWER(name) = LOWER('Jalón al pecho bilateral en máquina de palanca agarre supino');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/19d34RlUeHyvLh8s_HXc_DqyJeYNFiDxZ/view?usp=drive_link' WHERE LOWER(name) = LOWER('Remo pendlay prono');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/14LdkwWbOS0s_8Kll0EGuzJ0BE7VI9Rgt/view?usp=drive_link' WHERE LOWER(name) = LOWER('Bazman row desde polea media');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1VTpm9OeJlCdt7Nykodq9MlYo9uIpkGdF/view?usp=drive_link' WHERE LOWER(name) = LOWER('Remo ancho neutro ');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/16D3-6G4GxfRnLvg20amNC02bUFg9pis_/view?usp=drive_link' WHERE LOWER(name) = LOWER('Remo prono ancho ');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1HNoqIz_P0LMxu26ee8dDnTCbjow8bP-S/view?usp=drive_link' WHERE LOWER(name) = LOWER('Remo en T agarre prono ');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1qs3fskaLUgqyBRxkF3LaWLcCu_uqp5qX/view?usp=drive_link' WHERE LOWER(name) = LOWER('Remo bajo prono en máquina de palanca');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1RENy3cfmXpaJkUfcexnWxL8XcV4SN5VV/view?usp=drive_link' WHERE LOWER(name) = LOWER('Remo bajo neutro en máquina de palanca ');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1pEx_DxLnZxScupFfMWaKOjlifIguxops/view?usp=drive_link' WHERE LOWER(name) = LOWER('Remo agarre prono en máquina de palanca');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1vazqKqR9CugkTCQVEsxyS0_O_p9ZSjLR/view?usp=drive_link' WHERE LOWER(name) = LOWER('Remo con cuerda desde polea alta ');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1gY7V3SvXPGrpwxclKr0f3Iw-kej5NgI9/view?usp=drive_link' WHERE LOWER(name) = LOWER('Remo con cuerda desde polea alta con restricción banco a 75°');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1AfDyFn0JqWuIUNoahe0MUZ2wvl-ekbeI/view?usp=drive_link' WHERE LOWER(name) = LOWER('Remo meadows');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/18VKqAUaBKxFgNcbi4jcTy0yhcf1lsO1u/view?usp=drive_link' WHERE LOWER(name) = LOWER('Remo prono en multipower');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1UqnTO_lVSuYJhy12Pyt-xicawUUGN22j/view?usp=drive_link' WHERE LOWER(name) = LOWER('Jalón al pecho agarre neutro y ancho');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1xcUOeQAU4pwH4oX2QLhRvbmHQ5z269XY/view?usp=drive_link' WHERE LOWER(name) = LOWER('Jalón al pecho agarre prono ancho');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1l2L4HjxkJfcmnUOw9cteGbLy2vArMFSH/view?usp=drive_link' WHERE LOWER(name) = LOWER('Jalón al pecho en máquina de palanca');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1Z3v0v86T3X0UPM2rvZ5vA8_ADvIuhfTl/view?usp=drive_link' WHERE LOWER(name) = LOWER('Seal row agarre prono con mancuernas');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1T3H_NFRKpN4AQkIxQcp3fWnbE5YaRU67/view?usp=drive_link' WHERE LOWER(name) = LOWER('Seal row banco a 60° en multipower pecho apoyado');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1ODhPo8ivaYGLufeO5SM5NSfdaYesY9A9/view?usp=drive_link' WHERE LOWER(name) = LOWER('Hombro posterior en máquina ');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1cVzk4nXQmA6awmJuqFnkOjGqtVmUg4uq/view?usp=drive_link' WHERE LOWER(name) = LOWER('Hombro posterior agarre prono con mancuernas pecho apoyado en banco a 45°');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1-VpY3TCAIeksJRmQBf3ko6ypSmWHvp0v/view?usp=drive_link' WHERE LOWER(name) = LOWER('Hombro posterior sentado con mancuernas ');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1i4sYO8hwrJw5-AqlKpMXU7Wi_L247lz_/view?usp=drive_link' WHERE LOWER(name) = LOWER('Hang & Swing con mancuernas banco a 45º ');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1-g9DtexnwYI12t1V33kMKTo4bT4XVbWp/view?usp=drive_link' WHERE LOWER(name) = LOWER('Hombro posterior desde polea alta a dos brazos');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1PvrpTk6772rjm_qgTEH4Reb4BDl8OHjQ/view?usp=drive_link' WHERE LOWER(name) = LOWER('Hombro posterior desde polea alta a un brazo');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1i251sZpORt2sP5ldom-0pyGddXDJM4lc/view?usp=drive_link' WHERE LOWER(name) = LOWER('Hombro posterior desde polea alta con restricción banco a 60º');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1SNUUbwQW9u6WFiC8yYsgqsd8nCUwMVT0/view?usp=drive_link' WHERE LOWER(name) = LOWER('Híbrido entre remo y hombro posterior desde polea baja');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1Y0siT-PcjcSClRu8PbtUQs5DHdblG4H1/view?usp=drive_link' WHERE LOWER(name) = LOWER('Press banca inclinado a 45º en multipower ');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1q3OYFCK8WDm0otSpKIz7LZHnBB2mMBxb/view?usp=drive_link' WHERE LOWER(name) = LOWER('Press banca plano en multipower');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1STnJ4MNYk71Gy-53j_UQPbDGrplPt3kg/view?usp=drive_link' WHERE LOWER(name) = LOWER('Press banca inclinado a 45º con mancuernas');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1OThRrb0yB1xWR7x966dzV0useIbVCkza/view?usp=drive_link' WHERE LOWER(name) = LOWER('Press banca plano con mancuernas');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1ZZH_Fvsa2-V2AxZKH21kRxbMyx1VIpcI/view?usp=drive_link' WHERE LOWER(name) = LOWER('Press banca inclinado en máquina de palanca');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1C1AAdJMp678xpgu3Au1QsGzCYW2fPBqd/view?usp=drive_link' WHERE LOWER(name) = LOWER('Press banca plano en máquina de palanca');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1_syGBHjuNIKYTjGrkWv5L3YR6x79Zif3/view?usp=drive_link' WHERE LOWER(name) = LOWER('Press declinado en máquina de palanca agarre neutro');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1r_eoOovwdKYO8rXxuKGBHNYLyHCp8Gsg/view?usp=drive_link' WHERE LOWER(name) = LOWER('Press banca tumbado en máquina de palanca');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1gbF8v3bSQkYE2PfjyUtLDNZl8kShTB8d/view?usp=drive_link' WHERE LOWER(name) = LOWER('Press banca sentado en máquina de placas');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1UV5glE3yW7cF8zWgO88WiSLCv04t-8bg/view?usp=drive_link' WHERE LOWER(name) = LOWER('Press banca inclinado a 45º libre');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1gJU0FkqoQWxjakcBm1uJP0KUMOpOKi2k/view?usp=drive_link' WHERE LOWER(name) = LOWER('Press banca plano libre');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1VwqsstrYX47-6b3cXCcA5BxCtAMJQJRy/view?usp=drive_link' WHERE LOWER(name) = LOWER('Press Ben Yanes unilateral');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1mSmJQzWteoScYzseT-MQGtDwk_ZHhh1S/view?usp=drive_link' WHERE LOWER(name) = LOWER('Aperturas desde polea media banco a 75º');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1KWnzGHE-E_Ckd8heQevwHNzaQjdWNSOq/view?usp=drive_link' WHERE LOWER(name) = LOWER('Aperturas inclinadas desde polea baja banco a 45º');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1NLv_zAfME21g0b_nabcWXmvFDFbP45Hh/view?usp=drive_link' WHERE LOWER(name) = LOWER('Aperturas desde polea baja sentado en banco a 75º');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1CIijT2mZkemnAXiC4mjdZ3RQFOLxHJ83/view?usp=drive_link' WHERE LOWER(name) = LOWER('Aperturas desde polea baja de pie');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1ik7rXod0gmlg4JYOZGmVWBcvg9a4k91p/view?usp=drive_link' WHERE LOWER(name) = LOWER('Aperturas desde polea baja unilateral de pie');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1lzSJhSNWWOb4cmk8frRwAiJksU4DMB90/view?usp=drive_link' WHERE LOWER(name) = LOWER('Aperturas a 75º en máquina de palanca');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1sD3PrQHtD92_YR5hpaXKZPlx0glfd-Sf/view?usp=drive_link' WHERE LOWER(name) = LOWER('Aperturas en máquina de placas ');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1JGYGmz0EOIHb4ykWp2vrZ8jaGa7V6nIm/view?usp=drive_link' WHERE LOWER(name) = LOWER('Aperturas inclinadas en banco a 45º con mancuernas');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/15vzlMG-JBKMPbPOduv0B67tkIidsXECH/view?usp=drive_link' WHERE LOWER(name) = LOWER('Press militar en multipower sentado en banco a 75º');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1qNosIu1R0pQ6g2IVfVXy8va-fO83Ju9R/view?usp=drive_link' WHERE LOWER(name) = LOWER('Press militar unilateral sentado de lado en multipower');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/13UuhSOWHnUDJUljDxmmQ5zZ8N_9GypjP/view?usp=drive_link' WHERE LOWER(name) = LOWER('Press militar barra libre de pie');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1AJapzkQquLHri8zhb5JfCtfHgheqpSrB/view?usp=drive_link' WHERE LOWER(name) = LOWER('Press militar barra libre en rack banco a 75º');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1lMK-3Ghh1HaVhYnHNuQNyQJT8iauxRRD/view?usp=drive_link' WHERE LOWER(name) = LOWER('Press militar con mancuernas banco a 75º');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1w3Dh1gPk6MOgXDkgYRNoOlNWlAUoGGeC/view?usp=drive_link' WHERE LOWER(name) = LOWER('Press militar sentado al revés en máquina de palanca');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/12WKTCWmNvhGDd79V6-Xf8tqWV1q-BUom/view?usp=drive_link' WHERE LOWER(name) = LOWER('Press militar en máquina de placas');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1qMGX_jWrxGjzt_UmcefAw30O6MmAv7D9/view?usp=drive_link' WHERE LOWER(name) = LOWER('Elevaciones laterales con mancuernas de pie');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1sK4IEcQ7fjLlX_nCWRmAO187GBDFxkUE/view?usp=drive_link' WHERE LOWER(name) = LOWER('Elevaciones laterales sentado con mancuernas');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/14FEqy687q8MbPIRCDmQKPSxBTc5X_F0L/view?usp=drive_link' WHERE LOWER(name) = LOWER('Elevaciones laterales con restricción banco inclinado a 60º con mancuernas');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1pZl_FIQ1UyVYDtjC_Cb9JiDx6yqI7oDH/view?usp=drive_link' WHERE LOWER(name) = LOWER('Hombro lateral acostado de lado con mancuerna en banco inclinado a 45º ');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1IVKx5z1mV1h3yfYT0xJ8FW_VYXBUkcLE/view?usp=drive_link' WHERE LOWER(name) = LOWER('Elevaciones laterales en Y con restricción banco a 60º');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1YMXgNIIOzmCdXvBjWr4s2ZNVq_UQgAcZ/view?usp=drive_link' WHERE LOWER(name) = LOWER('Elevaciones laterales cruzadas desde polea media a dos brazos ');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1kzJs8k2ZhTn_Ad00SzQphHle8f6Y5_1O/view?usp=drive_link' WHERE LOWER(name) = LOWER('Elevación lateral desde polea media a un brazo');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/18y1eI2MoV4340bLN7zSNidRZMgdvU8HD/view?usp=drive_link' WHERE LOWER(name) = LOWER('Elevaciones laterales cruzadas desde polea baja a dos brazos ');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1j_D7kt-B2Cuemu3oJLBMteLKxC2J0gkX/view?usp=drive_link' WHERE LOWER(name) = LOWER('Hombro lateral tumbado en banco a 45º desde polea media con muñequeras');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1CnU2Dd5ItNnNCTju-fSyjlkNB7jdUFS3/view?usp=drive_link' WHERE LOWER(name) = LOWER('Hombro lateral desde polea baja con restricción en banco a 60º');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1AAOL1wQhJjyxhisLPhuv1GscH48qBrzV/view?usp=drive_link' WHERE LOWER(name) = LOWER('Six way con mancuernas de pie');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1Tei0T5HnZHB00saPffdqaJw0cztGC08G/view?usp=drive_link' WHERE LOWER(name) = LOWER('Six way sentado con mancuernas ');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1n3sL2T_vJa7DDLZjGnSfciI8KOUmkUDy/view?usp=drive_link' WHERE LOWER(name) = LOWER('Curl de bíceps con barra recta de pie');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1pX3hi9il3kemBnTRth84_NSUJYSeywV8/view?usp=drive_link' WHERE LOWER(name) = LOWER('Curl de bíceps barra Z agarre supino de pie');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1GvFCbys2tl28Pg66zzQA2js1VeTkPoYK/view?usp=drive_link' WHERE LOWER(name) = LOWER('Curl de bíceps barra Z agarre prono de pie');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1kh3NDOCqgD-KNwKj1cl_47WusZZthn0-/view?usp=drive_link' WHERE LOWER(name) = LOWER('Curl de bíceps desde polea baja con cuerda agarre supino');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1D4_RJ6rRVSsGxfRzINcT4Y_V6mx0vS35/view?usp=drive_link' WHERE LOWER(name) = LOWER('Curl de bíceps martillo desde polea baja con cuerda');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1Q_i-Iz_51FLgxUsCbGyAQWWedjJfJtaB/view?usp=drive_link' WHERE LOWER(name) = LOWER('Curl de bíceps desde polea baja con barra corta');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/12Tddu-PGoznBeqhbwogR662pdMaE82kb/view?usp=drive_link' WHERE LOWER(name) = LOWER('Curl de bíceps desde polea baja con barra corta agarre prono');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1lAtjdFm73KNb8lG3wS4L0IGMLpmnKUbL/view?usp=drive_link' WHERE LOWER(name) = LOWER('Curl Bayesian');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1S7DqliIGEfBocaiLik9izMZnICSx_I32/view?usp=drive_link' WHERE LOWER(name) = LOWER('Curl de bíceps unilateral brazo apoyado en banco a 75º desde polea baja');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1MEFewi2_xyH2YueGREAdLchDCOvKH_ma/view?usp=drive_link' WHERE LOWER(name) = LOWER('Curl de bíceps martillo con mancuernas bilateral de pie');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1Gue7mHPS4y_Ydx_Czt7LjQthQUheFKEX/view?usp=drive_link' WHERE LOWER(name) = LOWER('Curl de bíceps martillo con mancuernas alterno de pie');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1ablKOMRFMiMWcVRQloZrCuHgxBoDy0O6/view?usp=drive_link' WHERE LOWER(name) = LOWER('Curl de bíceps supino con mancuernas bilateral de pie');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1_BK644UMLi5CgWGuv5rPCP3WeKGRWFTC/view?usp=drive_link' WHERE LOWER(name) = LOWER('Curl de bíceps supino con mancuernas alterno de pie');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1EYlYLeyp4LLFZJU_iEud_C7pSX_RRv54/view?usp=drive_link' WHERE LOWER(name) = LOWER('Curl de bíceps Martillo con mancuernas alterno sentado en banco inclinado a 75º');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1IJwkpXxKhQwDgiWAtI942WObxpBxtUV1/view?usp=drive_link' WHERE LOWER(name) = LOWER('Curl de bíceps con mancuernas alterno sentado en banco inclinado a 75º');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1wmvlUHCjUo2t3oflU6T_wc-Wd1v5E49j/view?usp=drive_link' WHERE LOWER(name) = LOWER('Curl de bíceps concentrado unilateral con mancuerna');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1zymMOq9rFB_GzoGKfixD7ulDymbbBvgN/view?usp=drive_link' WHERE LOWER(name) = LOWER('Curl de bíceps tumbado banco a 45º con mancuernas');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1SyWNMoEIzdvvw47FGexvFq_pjvBhHW-V/view?usp=drive_link' WHERE LOWER(name) = LOWER('Spyder curl torso apoyado den manco a 45º');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1SFFVccn1-bx7ttvrsjk2ucSrRvlj9Cqb/view?usp=drive_link' WHERE LOWER(name) = LOWER('Curl de bíceps banco scott unilateral con mancuerna');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1KSoGX5MY_c7v_agXcveqCZrVXhblbnX0/view?usp=drive_link' WHERE LOWER(name) = LOWER('Curl de bíceps banco Scott Barra Z');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/10JfZ0BmOoLyJBIWKd8iP04mebNDemxrf/view?usp=drive_link' WHERE LOWER(name) = LOWER('Curl de bíceps en máquina de palanca sentado bilateral');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1nFqTBPlj8Hebkxuw581MJnupbgl6KX3J/view?usp=drive_link' WHERE LOWER(name) = LOWER('Curl de bíceps en máquina de palanca sentado unilateral');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1g3lNTPU5_0zX7L5DhaNRo8k_Ax_Izump/view?usp=drive_link' WHERE LOWER(name) = LOWER('Curl de bíceps en máquina de placas ');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1dzyGyBPMS0ppaV6ciuKonTYdU0kDW70R/view?usp=drive_link' WHERE LOWER(name) = LOWER('Press francés de espaldas a la polea alta con cuerda');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1cHIAkps13Z7-a7LI5C30JzvvH6I9VBvi/view?usp=drive_link' WHERE LOWER(name) = LOWER('Press francés de espaldas a la polea con barra corta ');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1KNrYMNCDA1doCKWOEvgCo9K0TNMzq4M4/view?usp=drive_link' WHERE LOWER(name) = LOWER('Press francés unilateral de espaldas a la polea alta');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1Fc7wA8uVEfWzA3PVvAu4lKWFqavv_Nkt/view?usp=drive_link' WHERE LOWER(name) = LOWER('Press francés con barra corta en banco inclinado a 30º desde polea baja');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1O08v0G0ZrbTH6B6kPKX94UM_p2N9GrAj/view?usp=drive_link' WHERE LOWER(name) = LOWER('Press francés con mancuernas banco inclinado a 30º');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1lN54M2KcU9fSO5GFT9kayT_cL3bOjXUI/view?usp=drive_link' WHERE LOWER(name) = LOWER('Press francés con mancuerna banco plano');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1SBodO1KEslZPckoqpEIYv6Zv4xE32_1f/view?usp=drive_link' WHERE LOWER(name) = LOWER('Press francés barra Z banco plano');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1O08v0G0ZrbTH6B6kPKX94UM_p2N9GrAj/view?usp=drive_link' WHERE LOWER(name) = LOWER('Press francés barra Z banco inclinado 30º');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1LIoRdindswHnpf6rB1i6IDJVwntyrf85/view?usp=drive_link' WHERE LOWER(name) = LOWER('Press francés unilateral tumbado con mancuerna');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1PNT7Dw8OwY7fYq6WepQ6lWN1FZldDzHU/view?usp=drive_link' WHERE LOWER(name) = LOWER('Press francés con mancuernas en el suelo');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1J-LJ36ZUlvDKNP6w17bgxEyIRF6ksKrq/view?usp=drive_link' WHERE LOWER(name) = LOWER('Press francés con barra Z en el suelo');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1ppB9wSf-WABfp8uGkamJ1kRWFVc4c3ft/view?usp=drive_link' WHERE LOWER(name) = LOWER('Extensión de tríceps desde polea alta con barra corta');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1tZdE86-gZgd0o2kIajSfcbeHHq_XiZkG/view?usp=drive_link' WHERE LOWER(name) = LOWER('Extensión de tríceps a un brazo desde polea alta de lado con muñequera ');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1MnnyGjExAI08nfnJQDURzfHYBMFozUEj/view?usp=drive_link' WHERE LOWER(name) = LOWER('Extensión de tríceps desde polea alta unilateral con muñequera');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1HQdlqHobr6UfaawKkaRNsWdhhGH_GJMC/view?usp=drive_link' WHERE LOWER(name) = LOWER('Extensión de tríceps unilateral desde polea alta con cuerda');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1tQGsq6T-llFeX-30F4k_300wuyiRDxtg/view?usp=drive_link' WHERE LOWER(name) = LOWER('Extensión de tríceps Katana');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1EvLmQMHnYruoNibG4yYZ0OnZp-MSa6OF/view?usp=drive_link' WHERE LOWER(name) = LOWER('Extensión de tríceps trasnuca unilateral con mancuerna de pie');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1pBIgtSzoXE_UxFRumD_zX_TSpX0LOunv/view?usp=drive_link' WHERE LOWER(name) = LOWER('Extensión de tríceps trasnuca sentado a dos brazos con mancuerna');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1LYhHvhwtnk9TYDTtIumX6MxJ8Ap6AXv-/view?usp=drive_link' WHERE LOWER(name) = LOWER('Extensiones de tríceps cruzadas desde polea estrecha');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1yA1ET5Cj1BO8F00NxGV8OhbFEwpRU131/view?usp=drive_link' WHERE LOWER(name) = LOWER('Extensiones de tríceps trasnuca cruzadas banco a 75º en polea estrecha');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1gCEeVF-_JlPrlYqvkEJjpuCg8P7xiCWk/view?usp=drive_link' WHERE LOWER(name) = LOWER('Kaz press en multipower');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1rqG4D1TksJomXcCAuQv26RnF8ll55T_x/view?usp=drive_link' WHERE LOWER(name) = LOWER('Kaz press en multipower banco inclinado a 30º ');
UPDATE exercises SET video_ref = 'https://drive.google.com/file/d/1sj5m1-fW919g1j-3wmqTbSOfUN1L6GUG/view?usp=drive_link' WHERE LOWER(name) = LOWER('Press cerrado para tríceps en multipower');

-- Total: 221 ejercicios actualizados
SELECT name, video_ref FROM exercises WHERE video_ref LIKE 'http%' LIMIT 10;